### ISSUE TITLE
Facing problem while sending data from one device to another using web socket

### ISSUE THREAD

**Issue by goyalish** [samsungsamiio/samsungsami.io#4]
Hi,
I created two devices with same device type.
I am trying to send some data from one device to another using web socket(say first device (sender)and second device (receiver).)
I can see the data is sent from source to SAMI (from data logs) but on the receiver end I am not getting it.
On the receiver side , web socket is properly open as I am getting ping from SAMI.
Below is the code snippet for the same.
I am using SAMILocatorMaster sample for this and made some changes
Sender side:
......
final String messageLatLng = JsonUtil.getDeviceMessage(Config.DEVICE_ID, Config.DDID, location);
........

if(websocket == null) {
            websocket = new Websocket();
        }
        if(websocket.isConnected()) {
            websocket.send(messageLatLng);
        }
        else {
            if(!websocket.isConnecting()) {
                websocket.connect(Config.WEBSOCKET_URL, new WebsocketEvents() {
                    @Override
                    public void onOpen(ServerHandshake handshakedata) {
                        websocket.send(JsonUtil.getRegisterMessage(Config.DEVICE_ID, Config.ACCESS_TOKEN));
                        websocket.send(JsonUtil.getRegisterMessage(Config.DDEVICE_ID, Config.DACCESS_TOKEN));
                        websocket.send(messageLatLng);
                    }

 public static String getDeviceMessage(String sdid, String ddid, Location location){
        JSONObject message = new JSONObject();
        try {
        	Double d = 1.242;//adding custom value 
            message.put(SOURCE_DEVICE, sdid);
            message.put(DESTINATION_DEVICE, ddid);
            message.put("type","message");
            message.put("cid", "17b86d582e36423888036fdbb2630492");
            JSONObject data = new JSONObject();
            data.put(LATITUDE, d);
            data.put(LONGITUDE, d);
            message.put(DATA, data);
        } catch (JSONException e) {
            e.printStackTrace();
        }
        return message.toString();
    }
This code is sending data to SAMI and I am getting mid as well

Receiver side:

if(websocket == null) {
                websocket = new Websocket();
            }
        
            else {
                if(!websocket.isConnecting()) {
                    websocket.connect(Config.LIVE_URL, new WebsocketEvents() {//));(using Second device id and device token in LIVE_URL)

                        @Override
                        public void onOpen(ServerHandshake handshakedata) {
                            websocket.send(JsonUtil.getRegisterMessage(Config.DEVICE_ID, Config.ACCESS_TOKEN));//using Second device id and device token tried with and without registration
                            
                        }

                        @Override
                        public void onMessage(String message) {
                        	setLiveText("Live onMessage(): " + message);
                            try {
                                JSONObject json = new JSONObject(message);
                                JSONObject dataNode = json.optJSONObject("data");
                                if(dataNode != null) {
                                    lastLat = dataNode.getString("lat");
                                    lastLng = dataNode.getString("lng");
                                }
                            } catch (JSONException e) {
                                // This message doesn't contain data node, might be a ping.
                        
                            }
                        }

I tried this as well for onOpen()

  @Override
                        public void onOpen(ServerHandshake handshakedata) {
                            websocket.send(JsonUtil.getRegisterMessage(Config.DEVICE_ID, Config.ACCESS_TOKEN));));//using Second device id and device token tried with and without registration

                            websocket.send(JsonUtil.getRegisterMessage(Config.SDEVICE_ID, Config.SACCESS_TOKEN));));//using First device id and device token tried with and without registration

                        }
WebSocket is opened properly as I am getting ping from SAMI.
Please let me know what needs to be done.
Regards

**Comment by yujingwu** [comment]
I will take a look. Thanks for reporting.

**Comment by yujingwu** [comment]
Before diving into technical stuff, I want to understand the logistics first.

This ticket is open against https://github.com/samsungsamiio/, which is open source SAMI developer documentation. However the ticket is not about documentation. I need to close this issue at this site and create  a new one in the correct site. Please address my questions below:

#1 Is this issue about the open source code for the sample application https://github.com/samsungsamiio/sample-android-SAMILocator ?

If the answer is YES, please open the issue in that site.

#2 If the answer is NO, this is general websocket question. Can you provide your email so that I can create a User Voice ticket? Or click Feedback button on the left (scroll down to see the button) on the following page then describe your issue. In that way, a User voice ticket is automatically created. https://developer.samsungsami.io/sami/sami-documentation/sending-and-receiving-data.html#live-streaming-data-with-websocket-api

**Comment by yujingwu** [comment]
It seems that you changed the code from https://github.com/samsungsamiio/sample-android-SAMILocator. You made a mistake in your modified code, which may contributed to the issue.

#1 For the receiving side, you are not supposed to send registration message in onOpen() method. Please consult the correct method in connectLiveWebsocket() in https://github.com/samsungsamiio/sample-android-SAMILocator/blob/master/SamiLocator/src/main/java/com/samsung/locator/SamiActivity.java

#2 At the sending side, getting mid only means the message has been received by SAMI. It does not mean the message has been validated against the Manifest. In the message cannot be validated (e.g. has incorrect format), it will be dropped by SAMI and wont be sent to the targeted devices. You should go to portal.samsungsami.io to see if the data is being streaming there lively as the following example https://developer.samsungsami.io/sami/demos-tools/your-first-iot-device.html#step-4-fire-it-up-and-view-the-data

#3 I do suggest you to try SAMILocator app by following the instructions in https://github.com/samsungsamiio/sample-android-SAMILocator and https://blog.samsungsami.io/mobile/development/2015/03/10/quick-apps-plot-your-location-in-real-time-with-sami.html

If you succeed there, it gives you the hint that your modified code or your device type may have problem. 

-------------------------
I am closing this issue since this has nothing to do with this repository for open source developer documentation. 

Should you have questions or issues, please file a ticket at the correct github repository or user voice by following my instructions in the comment above.
